name: CI

on:
  push:
    branches: [ universal2 ]
  pull_request:
    branches: [ universal2 ]

jobs:
  lint:
    name: Syntax Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install flake8
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Lint
      run: git diff HEAD^ | flake8 --diff --ignore=E501

  analyze:
    name: Analyze
    needs: lint
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript', 'python' ]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1

  build:
    name: Build Package
    needs: lint
    runs-on: macos-10.15
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build
        run: ./code/tools/make_munki_mpkg.sh -i dev.andre4ik3.managed.munki

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: munkitools
          path: ./munkitools-*.*.*.*.pkg
