# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Munki

on:
  push:
    branches: [ universal2 ]
  pull_request:
    branches: [ universal2 ]

jobs:
  lint:
    name: Syntax Check
    # straight up template from github, tysm
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install flake8
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Lint
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --ignore=E501 --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  Build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: ./code/tools/make_munki_mpkg.sh -i dev.andre4ik3.managed.munki
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: munkitools
          path: ./munkitools-*.*.*.*.pkg
